# Generated by Django 4.2.9 on 2024-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Title',
        ),
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
